// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrate/introspection should go through the direct (unpooled)
    // connection; the app itself (src/lib/prisma.ts) uses the pooled
    // DATABASE_URL for runtime queries.
    url: process.env["DIRECT_URL"],
  },
});
